CREATE TABLE IF NOT EXISTS hotel (
    hotel_id INT GENERATED BY DEFAULT AS IDENTITY,
    resort VARCHAR(255) NOT NULL,
    location VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    category VARCHAR(255) NOT NULL,
    description TEXT NOT NULL,
    food_type VARCHAR(255) NOT NULL,
    beach_distance INT NOT NULL,
    beach_type VARCHAR(255) NOT NULL,
    room_type VARCHAR(255) NOT NULL,
    conception VARCHAR(255) NOT NULL,
    minimal_price_per_night INT,

    PRIMARY KEY (hotel_id)
);

CREATE TABLE IF NOT EXISTS room (
    room_id INT GENERATED BY DEFAULT AS IDENTITY,
    hotel_id INT,
    price_per_night INT NOT NULL CHECK (price_per_night > 0),
    description TEXT NOT NULL,

    PRIMARY KEY (room_id),
    CONSTRAINT fk_hotel
        FOREIGN KEY (hotel_id)
        REFERENCES hotel(hotel_id)
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS hotel_photo (
    photo_id INT GENERATED BY DEFAULT AS IDENTITY,
    file_path VARCHAR(255) NOT NULL,
    hotel_id INT,

    PRIMARY KEY (photo_id),
    CONSTRAINT fk_hotel
        FOREIGN KEY (hotel_id)
        REFERENCES hotel(hotel_id)
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS hotel_service (
    hotel_service_id INT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) NOT NULL,
    hotel_id INT,

    PRIMARY KEY (hotel_service_id),
    CONSTRAINT fk_hotel
        FOREIGN KEY (hotel_id)
        REFERENCES hotel(hotel_id)
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS room_photo (
    photo_id INT GENERATED BY DEFAULT AS IDENTITY,
    file_path VARCHAR(255) NOT NULL,
    room_id INT,

    PRIMARY KEY (photo_id),
    CONSTRAINT fk_room
        FOREIGN KEY (room_id)
        REFERENCES room(room_id)
        ON DELETE CASCADE
);

CREATE TYPE ACCESS_LEVEL AS ENUM('viewer', 'editor', 'superadmin');

CREATE TABLE IF NOT EXISTS admin (
    admin_id INT GENERATED BY DEFAULT AS IDENTITY,
    access_level ACCESS_LEVEL NOT NULL,
    created_by_id INT,
    
    PRIMARY KEY (admin_id),
    CONSTRAINT fk_created_by_admin
        FOREIGN KEY (created_by_id)
        REFERENCES admin(admin_id)
        ON DELETE SET NULL
);

CREATE OR REPLACE FUNCTION update_minimal_hotel_price()
RETURNS TRIGGER
LANGUAGE PLPGSQL
AS
$$
BEGIN
UPDATE hotel
SET minimal_price_per_night = COALESCE((
    SELECT MIN(price_per_night)
    FROM room
    WHERE room.hotel_id = COALESCE(NEW.hotel_id, OLD.hotel_id)
), minimal_price_per_night)
WHERE hotel_id = COALESCE(NEW.hotel_id, OLD.hotel_id);
RETURN NULL;
END;
$$;

CREATE TRIGGER trigger_update_minimal_hotel_price
AFTER INSERT OR UPDATE OF price_per_night OR DELETE
ON room
FOR EACH ROW
EXECUTE FUNCTION update_minimal_hotel_price();



